### PR TITLE
BIDE miner v0

### PR DESCRIPTION
**Pull request by remiadon**
This PR is a code import from https://github.com/chuanconggao/PrefixSpan-py

Inclusion has been discussed in https://github.com/chuanconggao/PrefixSpan-py/issues/33

### CODE REVIEW

**Comment by chuanconggao** [comment]
One question here. If code is rewritten here, eventually it would diverge from the original implementation. If there is any bug fix, it needs to go to two places. Just want to make sure maintainability is covered. Thanks.

**Comment by remiadon** [comment]
@chuanconggao thanks for responding

The code living in skmine will diverge from the original implementation, for sure. If bugs fixes/refactoring is coming soon, maybe we can leave this PR pending until a more stable release is ready on your side. This way both repositories would take the benefits

Another option is to make your codebase respect the scikit-mine API. The resulting implementation would only live in one place (your repo) but would be compatible. I can guide you through this if you like.

NB:  I am presenting all possible options. Your opinion is important so I'd rather not impose a methodology

**Comment by chuanconggao** [comment]
Thanks. 

I feel like the relationship of two packages are like below
- The original one is reference implementation with richer set of features specifically for sequence pattern mining. 
- The scikit-mine one is for broader use cases of all kinds of pattern mining, but may not provide specific advanced feature in original one in initial phase. 

One open question is how would scikit-mine support other use cases in future, like graph pattern mining? Would it reimplement or just wrap existing packages (assuming there is a good one). 

I agree that it is best to wait for refactoring in original package before this specific PR. In the meanwhile, we can explore how other popular packages deal with this. One popular approach is supporting plugins. Ultimately, the best approach is the one that can grow the package usage/coverage in organic way.

**Comment by chuanconggao** [comment]
> Another option is to make your codebase respect the scikit-mine API. The resulting implementation would only live in one place (your repo) but would be compatible. I can guide you through this if you like.

This is interesting. It is easy to support a wrapper API (in either repo). Do you have more details/examples?

**Comment by remiadon** [comment]
> One open question is how would scikit-mine support other use cases in future, like graph pattern mining? Would it reimplement or just wrap existing packages (assuming there is a good one).

Graph algorithms are in our roadmap, so "reimplementing" them is the most likely to happen

------------

> In the meanwhile, we can explore how other popular packages deal with this. One popular approach is supporting plugins. Ultimately, the best approach is the one that can grow the package usage/coverage in organic way.

The most popular example I can think of is scikit-learn. Scikit-learn defines an API via base classes and mixins, and one can provide a "plug-in" by extending these classes. scikit-mine extends the API provided by scikit-learn. In our case, `prefixspan` can extend the base classes defined in [this file of skmine](https://github.com/scikit-mine/scikit-mine/blob/master/skmine/base.py)

------------

> This is interesting. It is easy to support a wrapper API (in either repo). Do you have more details/examples?

Below are examples with code
with the current behaviour
```python
>> from prefixspan import PrefixSpan
>> db = [
     [0, 1, 2, 3, 4],
     [1, 1, 1, 3, 4],
     [2, 1, 2, 2, 0],
     [1, 1, 1, 2, 2],
] 
>> ps = PrefixSpan(db)
>> print(ps.frequent(2, closed=True))
[(2, [0]), (4, [1]), (3, [1, 2]), (2, [1, 2, 2]), (2, [1, 3, 4]), (2, [1, 1, 1])]
>> print(ps.topk(5, closed=True))
[(4, [1]), (3, [1, 2]), (2, [1, 1, 1]), (2, [1, 2, 2]), (2, [1, 3, 4])]
```

and with skmine compatibility, this would look like
```python
>> from prefixspan import BIDE
>> db = [
     [0, 1, 2, 3, 4],
     [1, 1, 1, 3, 4],
     [2, 1, 2, 2, 0],
     [1, 1, 1, 2, 2],
] 
>> bide = BIDE(min_supp=2)
>> bide.fit(db)  # now `bide` stores informations about the database to perform the mining
>> bide.discover()
(0, )          2
(1)            4
(1, 2)         3
(1, 2, 2)      2
(1, 3, 4)      2
(1, 1, 1)      2
dtype: int64

>> bide.discover(k=5)   # top k discovery
(1, )          4
(1, 2)         3
(1, 1, 1)      2
(1, 2, 2)      2
(1, 3, 4)      2
dtype: int64

**Comment by chuanconggao** [comment]
Thanks for sharing the details. 

Seems like the wrapper API approach is cleaner and easier to maintain in my opinion, given that the original one would still receive improvements in long run.

Anyway, let me refactor on original package, while we can further discuss the new API layer for scikit-mine in parallel.

**Comment by chuanconggao** [comment]
BTW, is the roadmap maintained anywhere? Would suggest making it public for easier contributions. For example, I am personally interested in algorithms on sliding window.

**Comment by remiadon** [comment]
@chuanconggao 

> Seems like the wrapper API approach is cleaner and easier to maintain in my opinion, given that the original one would still receive improvements in long run.

Agreed !!

> Anyway, let me refactor on original package, while we can further discuss the new API layer for scikit-mine in parallel.

Waiting for your inputs then :) 

> BTW, is the roadmap maintained anywhere? Would suggest making it public for easier contributions. For example, I am personally interested in algorithms on sliding window.

You just reminded me I had to do this. I'll push it this week, on a dedicated page, and keep your informed

Thanks for all

**Comment by remiadon** [comment]
@chuanconggao just for curiousity, what do you mean by "sliding window" ?
Any reference or paper to share ?

**Comment by chuanconggao** [comment]
> @chuanconggao just for curiousity, what do you mean by "sliding window" ?
> 
> Any reference or paper to share ?

For example, this one https://dblp.org/rec/conf/cikm/GaoW09

Basically, the dataset is now bounded by a sliding window and it is to find patterns efficiently based on prior knowledge of the previous window, without re-mining the whole dataset.

**Comment by remiadon** [comment]
closing this for maintenance

**Pull request closed without merging**
