### PR TITLE
Lcm v2

### PR DESCRIPTION
**Pull request by remiadon**
New features for a wider usage of LCM

- [x] max_depth parameters to reduce the search space
- [x] depth as an extra information in the output of `discover`
- [ ] performance enhancements if possible

### CODE REVIEW

**Comment by remiadon** [comment]
@lgalarra this should be almost ready

**Comment by remiadon** [comment]
and Here is the usage
```python
        >>> from skmine.itemsets import LCM
        >>> D = [[1, 2, 3, 4, 5, 6], [2, 3, 5], [2, 5]]
        >>> LCM(min_supp=2).fit_discover(D)
             itemset  support
        0     (2, 5)        3
        1  (2, 3, 5)        2
        >>> LCM(min_supp=2).fit_discover(D, return_tids=True, return_depth=True)
             itemset       tids depth
        0     (2, 5)  [0, 1, 2]     0
        1  (2, 3, 5)     [0, 1]     1
```

**Comment by remiadon** [comment]
@lgalarra I also have one concern about output format. For the moment the resulting dataframe has a postional index, and itemsets have a dedicated column.

SLIM on the other hand, return a pandas Series with itemsets in the index itself.

Would that be an interesting feature if itemsets (eg. (2, 3, 5) in the example above) could be retrieved by key
That would make accessing attribute for a specific pattern way easier, like so
```python
>>> patterns = LCM().fit_discover(D)
                   support
          (2, 5)         3
       (2, 3, 5)         2
>>>patterns.loc[(1, 2, 3)].support
3
```

**Comment by remiadon** [comment]
and another question @lgalarra 

What syntax do you use ?
```python
LCM().fit_discover(D, return_tids=True)
#OR
LCM().fit(D).discover(return_tids=True)
```

**Comment by lgalarra** [comment]
As I suggested in #89, max_depth should be set by default to "infinite", or to `sys.maxsize` in integer terms.  What do you think?

In regards to 

https://github.com/scikit-mine/scikit-mine/pull/90#issuecomment-743099086

I would vote for the second syntax as it decouples the tasks of "fit" and "discover". I can imagine a user running `fit` once and then `discover` with different arguments (as this list may grow throughout time).  However I have a question, in which scenarios could a user `run` fit without `discover`?

**Comment by lgalarra** [comment]
> @lgalarra I also have one concern about output format. For the moment the resulting dataframe has a postional index, and itemsets have a dedicated column.
> 
> SLIM on the other hand, return a pandas Series with itemsets in the index itself.
> 
> Would that be an interesting feature if itemsets (eg. (2, 3, 5) in the example above) could be retrieved by key
> That would make accessing attribute for a specific pattern way easier, like so
> 
> ```python
> >>> patterns = LCM().fit_discover(D)
>                    support
>           (2, 5)         3
>        (2, 3, 5)         2
> >>>patterns.loc[(1, 2, 3)].support
> 3
> ```

Ohh.. I think indexing by pattern makes perfect sense (looks elegant).

**Comment by remiadon** [comment]
> As I suggested in #89, max_depth should be set by default to "infinite", or to sys.maxsize in integer terms. What do you think?

Well the only issue I see with this is that LCM is internally doing recursive calls. CPython has a built-in recursion depth limit, so if by any turn of fate the mining goes above this limit then LCM will inelegantly crash
For this the best compromise is to set `max_depth=100`, this will give us practical guarantees :) 

---------

> I would vote for the second syntax as it decouples the tasks of "fit" and "discover". I can imagine a user running fit once and then discover with different arguments (as this list may grow throughout time). However I have a question, in which scenarios could a user run fit without discover?

### Pros and cons for both solutions
##### fit_discover() only
- make extra performance optimisations possible (as we can access the data itself at discover time)
- make LCM a pure black Class that acts as a single function ..

##### fit() and discover() separated
- separate implementation and documentation for both
- make a partial_fit() implementation possible (increment internal data representation), but do we really need it ?
- only work with a vertical representation of the original data, which disable potential optimizations ....

To me we should not think too much about run-time performance, but focus on usage. LCM is here to allow general purpose mining. Algorithms like SLIM are designed to be performant. On the other hand, why allowing separate calls to `fit` and `predict` if never used in practice ??

@lgalarra what do you think ?

**Comment by lgalarra** [comment]
Hi Rémi,

> 
> Well the only issue I see with this is that LCM is internally doing recursive calls. CPython has a built-in recursion depth limit, so if by any turn of fate the mining goes above this limit then LCM will inelegantly crash
> For this the best compromise is to set max_depth=100, this will give us practical guarantees :)

I see your point. Then setting max_depth=100 seems reasonable. Is an iterative LCM implementation envisaged in the future?

> On the other hand, why allowing separate calls to fit and predict if never used in practice ??

Based on all your arguments, it seems that having a single method has more advantages than pitfalls. That said, a scenario that might justify decoupling `fit` and `discover` is discriminant pattern mining: assuming that the subsets of the different classes have the same "schema", then we could run `fit` once, on one of the classes or on a sample, and `discover` on the different classes. I suppose that the only requirement is to do that would be to ensure that `fit` has seen all the items.

**Comment by remiadon** [comment]
@lgalarra 

> Is an iterative LCM implementation envisaged in the future?

If you have pseudo code somewhere why not, but I am really not sure about the performance gain

> That said, a scenario that might justify decoupling fit and discover is discriminant pattern mining: assuming that the subsets of the different classes have the same "schema", then we could run fit once, on one of the classes or on a sample, and discover on the different classes

For now LCM is designed to perform discovery on the data it has been fitted on. The `discover` function should not have any data parameter, only runtime specific parameters, i.e DISCOVERY IS NOT INFERENCE
It's not clear to me as  you want to "discover on the different classes"

**Comment by lgalarra** [comment]
> For now LCM is designed to perform discovery on the data it has been fitted on. The discover function should not have any data parameter, only runtime specific parameters, i.e DISCOVERY IS NOT INFERENCE
> It's not clear to me as you want to "discover on the different classes"

My mistake, I had forgotten that discovery does not take any argument. You can ignore my comment.

**Pull request merged**
